### ISSUE TITLE
initContainer breaking access to repositories when using Projects

### ISSUE THREAD

**Issue by gsantovena** [SchwarzIT/node-red-chart#106]
### What happened?

When the [Projects](https://nodered.org/docs/user-guide/projects/) are enabled and a pod is replaced with another one, the init container added in [PR#28](https://github.com/SchwarzIT/node-red-chart/pull/28) changes the access of all the files in `/data` to `777`, which also changes the ssh keys which should be `600`, losing access to the repositories.

A workaround is to re-create the ssh keys within the GUI but that's not ideal.

### How can we reproduce this?

- Create a new deployment using this chart and specifying to use "projects":
```
projects: {
    /** To enable the Projects feature, set this value to true */
    enabled: true,
    workflow: {
        mode: "manual"
    }
},
```
- Enable persistence by using an existing claim.
- Log into node-red.
- Configure user account and ssh keys.
- Create a new project by creating/cloning a repository.
- Work and push the changes to the repository.
- Terminate the pod.
- Try to sync.

### Helm Chart version

```bash
$ helm list --namespace staging | grep nodered
nodered                                 	staging  	1       	2022-04-12 09:12:36.887073322 -0700 -0700	deployed	node-red-0.15.4 	2.2.2
```
```


### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

**Comment by dirien** [comment]
Hi @gsantovena,

thanks for reporting! Let me reproduce it with your steps.

**Comment by dirien** [comment]
Hi @gsantovena,

I removed the initContainer. With runAsUser and fsgroup there is no need to recursivle chmod all files. Now the PV gets mounted with the correct userid and group.

Version 0.17.0 for the new Helm Chart. 

Please let me know, if there is any issues.
