### ISSUE TITLE
Is HA possible?

### ISSUE THREAD

**Issue by dberardo-com** [SchwarzIT/node-red-chart#171]
### Is your feature request related to a problem? Please describe.

I am not familiar to where the nodered stores information but i see a "replicaCount" attribute for this chart, so i wonder:
* is high-availability possible with this chart?
* how can applications/flows be deduplicated if replicaCount is > 1 ? is there a way to let them run only once?
* is possible to achieve HA saving information in an external HA-database cluster?

regards

### Describe the solution you'd like

HA

### Describe alternatives you've considered

Serverless frameworks

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Hi @dberardo-com,

thanks for posting the issue. Currently the chart does not support an HA setup of node-red.

We should possible make the `replicaCount` not configurable to avoid any confusions.

**Comment by dirien** [comment]
Hi @dberardo-com,

With https://github.com/SchwarzIT/node-red-chart/pull/180, we going to remove the option to configure the `replicaCount` to avoid any misunderstanding regarding a possible HA option of this Helm Chart.

**Comment by dberardo-com** [comment]
ok thanks, i assume that HA is in general not possible in node-red, regardless of this helm chart right ? just to confirm
