### ISSUE TITLE
Readiness for built-in https scheme support

### ISSUE THREAD

**Issue by mbaykara** [SchwarzIT/node-red-chart#246]
### What happened?

Let's consider a scenario where a Node-RED instance is configured with enabled https for some specific reason. In this case, the hard-enabled readiness check does not receive a 200 response because the scheme is set to http. As a result, the pod will not transition to the ready state.

### How can we reproduce this?

To enhance the functionality, please consider the following revisions:

* Enable HTTPS with self-signed certificates. In my opinion, liveness and readiness should not be enabled by default. The user of the chart should have the ability to enable or disable them or further configure.
Furthermore, it would be beneficial to take into account the following aspects:
* Make the mount point data configurable.
* Allow for configurability of the SecurityContext. Currently, modifying any item requires modification of all items, unless the default settings are acceptable.
* The original Node-RED image is configured with a default user ID of 1000. What is the reasoning behind changing it to 10003?
* When ingress is enabled with TLS, a certificate object is automatically created. However, what should be done if a self-signed certificate is required for internal usage?

It appears that this chart has been designed for a specific use case and may no longer serve a general purpose.### Helm Chart version

```bash
0.24.1
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Hey @mbaykara,

thanks for the creating the issue and providing some valuable feedback.

Feel free start contributing your points into this codebase! This will help to make this chart an even better experience for the whole community.

On PR for each of your points would be great, as it is fast to review and incremental add new features!

**Comment by dirien** [comment]
@mbaykara, closing this for now. Feel free to open the PRs if you want to tackle on this.
