### ISSUE TITLE
Implement computed annotations for 

### ISSUE THREAD

**Issue by dblencowe** [SchwarzIT/node-red-chart#264]
### Is your feature request related to a problem? Please describe.

In order to deploy this chart to my cluster successfully I need to add annotations to the service created

### Describe the solution you'd like

Implement `.Values.service.annotations` in a fully backwards-compatible way

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Happy to submit the PR for this if wanted

**Comment by dblencowe** [comment]
Thanks Dirien! Really hope I got everything in the contributing guide right!

**Comment by dirien** [comment]
@dblencowe sure you are! Maybe you need to bump the version in the `Chart.yaml`

**Comment by dblencowe** [comment]
Sorry! Didn't realise I should do that in my PR. Updating now
